import type { Event } from "@/entities/event";

export const mockEvents: Event[] = [
	{
		id: "1",
		projectId: "demo-project",
		level: "error",
		message: "TypeError: Cannot read property 'map' of undefined",
		url: "https://example.com/dashboard",
		timestamp: new Date(Date.now() - 1000 * 60 * 5),
		userId: "user_123",
		stack: `TypeError: Cannot read property 'map' of undefined
    at UserDashboard.render (UserDashboard.tsx:45:12)
    at ReactDOMComponent.render (react-dom.development.js:12345:23)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (react-dom.development.js:12345:23)
    at ReactCompositeComponentWrapper._renderValidatedComponent (react-dom.development.js:12345:23)
    at ReactCompositeComponentWrapper.performInitialMount (react-dom.development.js:12345:23)
    at ReactCompositeComponentWrapper.mountComponent (react-dom.development.js:12345:23)
    at Object.mountComponent (react-dom.development.js:12345:23)
    at ReactDOMComponent.mountChildren (react-dom.development.js:12345:23)
    at ReactDOMComponent._createInitialChildren (react-dom.development.js:12345:23)
    at ReactDOMComponent.mountComponent (react-dom.development.js:12345:23)`,
		context: {
			component: "UserDashboard",
			props: {
				userId: "user_123",
				filters: { status: "active" },
			},
			state: {
				users: null,
				loading: false,
			},
			error: "Attempted to call map on undefined users array",
		},
		userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
		sessionId: "sess_abc123",
		metadata: {
			environment: "production",
			version: "1.2.3",
			build: "2024-01-15",
			featureFlags: ["new-dashboard", "analytics-v2"],
		},
		screenshotUrl: null,
		clickTrace: null,
		performance: {
			loadTime: 1234,
			renderTime: 567,
			memoryUsage: 45678901,
		},
		createdAt: new Date(Date.now() - 1000 * 60 * 5),
	},
	{
		id: "2",
		projectId: "demo-project",
		level: "warn",
		message: "Deprecated API method used: oldMethod()",
		url: "https://example.com/products",
		timestamp: new Date(Date.now() - 1000 * 60 * 15),
		userId: "user_456",
		stack: null,
		context: null,
		userAgent:
			"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
		sessionId: "sess_def456",
		metadata: null,
		screenshotUrl: null,
		clickTrace: null,
		performance: null,
		createdAt: new Date(Date.now() - 1000 * 60 * 15),
	},
	{
		id: "3",
		projectId: "demo-project",
		level: "info",
		message: "User completed checkout process",
		url: "https://example.com/checkout",
		timestamp: new Date(Date.now() - 1000 * 60 * 30),
		userId: "user_789",
		stack: null,
		context: null,
		userAgent:
			"Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15",
		sessionId: "sess_ghi789",
		metadata: null,
		screenshotUrl: null,
		clickTrace: null,
		performance: null,
		createdAt: new Date(Date.now() - 1000 * 60 * 30),
	},
	{
		id: "4",
		projectId: "demo-project",
		level: "error",
		message: "Network request failed: POST /api/users",
		url: "https://example.com/api/users",
		timestamp: new Date(Date.now() - 1000 * 60 * 45),
		userId: null,
		stack: null,
		context: null,
		userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0",
		sessionId: "sess_jkl012",
		metadata: null,
		screenshotUrl: null,
		clickTrace: null,
		performance: null,
		createdAt: new Date(Date.now() - 1000 * 60 * 45),
	},
	{
		id: "5",
		projectId: "demo-project",
		level: "debug",
		message: "Component rendered: UserProfile",
		url: "https://example.com/profile",
		timestamp: new Date(Date.now() - 1000 * 60 * 60),
		userId: "user_012",
		stack: null,
		context: null,
		userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36",
		sessionId: "sess_mno345",
		metadata: null,
		screenshotUrl: null,
		clickTrace: null,
		performance: null,
		createdAt: new Date(Date.now() - 1000 * 60 * 60),
	},
	{
		id: "6",
		projectId: "demo-project",
		level: "info",
		message: "Page visit tracked: /products",
		url: "https://example.com/products",
		timestamp: new Date(Date.now() - 1000 * 60 * 90),
		userId: "user_345",
		stack: null,
		context: null,
		userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/120.0.0.0",
		sessionId: "sess_pqr678",
		metadata: null,
		screenshotUrl: null,
		clickTrace: null,
		performance: null,
		createdAt: new Date(Date.now() - 1000 * 60 * 90),
	},
	{
		id: "7",
		projectId: "demo-project",
		level: "warn",
		message: "Slow API response detected: 3.5s",
		url: "https://example.com/api/data",
		timestamp: new Date(Date.now() - 1000 * 60 * 120),
		userId: null,
		stack: null,
		context: null,
		userAgent:
			"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1.15",
		sessionId: "sess_stu901",
		metadata: null,
		screenshotUrl: null,
		clickTrace: null,
		performance: null,
		createdAt: new Date(Date.now() - 1000 * 60 * 120),
	},
	{
		id: "8",
		projectId: "demo-project",
		level: "error",
		message: "Unhandled promise rejection: Failed to load user data",
		url: "https://example.com/dashboard",
		timestamp: new Date(Date.now() - 1000 * 60 * 150),
		userId: "user_678",
		stack: null,
		context: null,
		userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/121.0",
		sessionId: "sess_vwx234",
		metadata: null,
		screenshotUrl: null,
		clickTrace: null,
		performance: null,
		createdAt: new Date(Date.now() - 1000 * 60 * 150),
	},
];

